### ISSUE TITLE
Auto-completion not working for positional arguments with bash

### ISSUE THREAD

**Issue by rkpattnaik780** [redhat-developer/app-services-cli#554]
## Description

**Version**: 0.21.0

### Steps to reproduce

1. Enable completion for Bash.
2. After logging in, select a kafka nstance with `./rhoas kafka use`.
3. Try to run `describe` command, instead of typing the name of entire topic, press tab(which should trigger auto-completion).

### Expected vs actual behaviour

Bash will display list of directories in the current directory when a list of topics should've been displayed.

![Screenshot from 2021-04-09 14-47-09](https://user-images.githubusercontent.com/23582438/114346829-acf8b900-9b81-11eb-81de-606a766c2d2e.png)

**Comment by craicoverflow** [comment]
@rkpattnaik780 I can't reproduce this. Maybe it is fixed now since https://github.com/redhat-developer/app-services-cli/releases/tag/0.23.0-alpha4 was released. Could you try again using this release?

**Comment by craicoverflow** [comment]
Ah, it is working for me for kafka commands, but not for the topic commands! Is it the same for you?

**Comment by rkpattnaik780** [comment]
Quickly checked with `kafka describe` and `kafka delete`, the problem persists. Folder names are being suggested.
